### ISSUE TITLE
Если оба работают, и команда /planet и чат, то ок, ничего не меняй. :)

### ISSUE THREAD

**Issue by denis-trofimov** [Macsmoreno/mybot#1]
https://github.com/Macsmoreno/mybot/blob/96240c8232062241c829d9be05bec194bec488ed/bot.py#L68-L72

В старых версиях надо было писать MessageHandler после CommandHandler, иначе не работал CommandHandler.

**Comment by Macsmoreno** [comment]
Бот полностью работает.)
